backend:
  name: github
  repo: phongduong/my-portfolio
# publish_mode: editorial_workflow
site_url: https://phongduong.me
display_url: https://phongduong.me
logo_url: https://phongduong.me/logo.svg
media_folder: "portfolio/.vuepress/public/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Post"
    name: "post"
    folder: "portfolio/posts"
    create: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "PostLayout",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Publish Date",
          name: "publish_date",
          widget: "date",
          format: "MM-DD-YYYY",
        }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          default: "project",
          options:
            [
              { label: "Project", value: "project" },
              { label: "Programming", value: "programming" },
              { label: "Life", value: "life" },
              { label: "Idea", value: "idea" },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Contact"
        name: "contact"
        file: "portfolio/contact.md"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "ContactLayout",
            }
          - { label: Title, name: title, widget: string, default: "Contact" }
          - label: "Contact Information"
            name: "contact_information"
            widget: "list"
            allow_add: true
            field:
              - label: Contact
                name: contact
                widget: object
                fields:
                  - { label: Type, name: type, widget: string }
                  - { label: URL, name: url, widget: string }
      - label: "Projects"
        name: "projects"
        file: "portfolio/projects.md"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "ProjectsLayout",
            }
          - { label: Title, name: title, widget: string, default: "Projects" }
          - label: "Project Information"
            name: "project_information"
            widget: "list"
            allow_add: true
            field:
              - label: Project
                name: project
                widget: object
                fields:
                  - { label: Name, name: name, widget: string }
                  - { label: Description, name: description, widget: text }
                  - { label: URL, name: url, widget: string }
