backend:
  name: github
  repo: phongduong/my-portfolio
site_url: https://phongduong.netlify.com
display_url: https://phongduong.netlify.com
logo_url: https://phongduong.netlify.com/img/logo.png
media_folder: portfolio/.vuepress/public/uploads
public_folder: /uploads
collections:
  - label: Post
    name: post
    folder: portfolio/posts
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - {
          label: Date,
          name: date,
          widget: date,
          format: MM-DD-YYYY,
        }
      - { label: Body, name: body, widget: markdown }
  - label: Pages
    name: pages
    files:
      - label: Contact
        name: contact
        file: portfolio/contact.md
        fields:
          - {
              label: Layout,
              name: layout,
              widget: hidden,
              default: OtherLayout,
            }
          - { label: Title, name: title, widget: string, default: Contact }
          - label: Contact
            name: contact
            widget: list
            allow_add: true
            fields:
              - { label: Name, name: name, widget: string }
              - { label: URL, name: url, widget: string }

      - label: Projects
        name: projects
        file: portfolio/projects.md
        fields:
          - {
              label: Layout,
              name: layout,
              widget: hidden,
              default: OtherLayout,
            }
          - { label: Title, name: title, widget: string, default: Projects }
          - label: Projects
            name: projects
            widget: list
            allow_add: true
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: text }
              - { label: URL, name: url, widget: string }
