backend:
  name: github
  repo: phongduong/my-portfolio
# publish_mode: editorial_workflow
site_url: https://phongduong.me
display_url: https://phongduong.me
logo_url: https://phongduong.me/logo.svg
media_folder: "portfolio/.vuepress/public/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Post"
    name: "post"
    folder: "portfolio/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Publish Date",
          name: "publish_date",
          widget: "date",
          format: "MM-DD-YYYY",
        }
      - {label: "Layout", name: "layout", widget: "hidden", default: "PostLayout"}
      - {
          label: "Tag",
          name: "tag",
          widget: "select",
          default: "programming",
          options:
            [
              { label: "Programming", value: "programming" },
              { label: "Life", value: "life" },
              { label: "Idea", value: "idea" },
              { label: "Project", value: "project" },
            ],
        }
      - { label: "Content", name: "content", widget: "markdown" }
