backend:
  #
  # prod congfigure
  #
  # name: git-gateway
  # accept_roles:
  #   - admin

  #
  # dev configure
  #
  name: github
  repo: phongduong/my-portfolio

  branch: master
# publish_mode: editorial_workflow
media_folder: ".vuepress/public/images/upload"
public_folder: "images/upload"
logo_url: https://phongduong.me/images/logo.png
collections:
  - name: "idea"
    label: "Idea"
    folder: "portfolio/ideas"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_idea_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Status",
          name: "status",
          widget: "select",
          options: ["idea", "project"],
        }
      - {
          label: "Project",
          name: "project",
          widget: "relation",
          required: false,
          collection: "project",
          searchFields: ["title", "slug"],
          valueField: "slug",
          displayFields: ["title", "slug"],
        }
      - {
          label: "Publish date",
          name: "publish_date",
          widget: "date",
          format: "DD/MM/YYYY",
        }
      - { label: "Idea content", name: "body", widget: "markdown" }

  - name: "project"
    label: "Project"
    folder: "portfolio/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_project_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Public URL", name: "public-url", widget: "string" }
      - {
          label: "Publish date",
          name: "publish_date",
          widget: "date",
          format: "DD/MM/YYYY",
        }
      - {
          label: "Idea",
          name: "idea",
          widget: "relation",
          collection: "idea",
          searchFields: ["title", "slug"],
          valueField: "title",
          displayFields: ["title", "slug"],
        }
      - { label: "Project content", name: "body", widget: "markdown" }

  - name: "progress"
    label: "Progress"
    folder: "portfolio/progresses"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_progress_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Publish date",
          name: "publish_date",
          widget: "date",
          format: "DD/MM/YYYY",
        }
      - { label: "Progress content", name: "body", widget: "markdown" }
      - {
          label: "Project",
          name: "project",
          widget: "relation",
          collection: "project",
          searchFields: ["title", "slug"],
          valueField: "slug",
          displayFields: ["title", "slug"],
        }
