backend:
  name: github
  repo: phongduong/my-portfolio
publish_mode: editorial_workflow
site_url: https://phongduong.me
display_url: https://phongduong.me
logo_url: https://phongduong.me/logo.svg
media_folder: "portfolio/.vuepress/public/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Blog"
    name: "blog"
    folder: "portfolio/blogs"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "publish_date", widget: "date" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          default: "programming",
          options:
            [
              { label: "Programming", value: "programming" },
              { label: "Life", value: "life" },
              { label: "Idea", value: "idea" },
              { label: "Project", value: "project" },
            ],
        }
      - { label: "Content", name: "content", widget: "markdown" }
