backend:
  name: github
  repo: phongduong/my-portfolio
site_url: https://phongduong.dev
display_url: https://phongduong.dev
logo_url: ../image/logo.png
media_folder: static/uploads
public_folder: /uploads
publish_mode: editorial_workflow
collections:
  - label: Post
    name: post
    folder: data/posts
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - {
          label: Tag,
          name: tag,
          widget: relation,
          collection: tag,
          valueField: title,
          searchFields: [title],
          default: me
        }
      - { label: Body, name: body, widget: markdown }
  - label: Tag
    name: tag
    folder: data/tags
    create: true
    fields:
      - { label: Title, name: title, widget: string }
  - label: Pages
    name: pages
    files:
      - label: Contact
        name: contact
        file: data/contact.md
        fields:
          - { label: Title, name: title, widget: string, default: Contact }
          - label: Contact
            name: contact
            widget: list
            allow_add: true
            fields:
              - { label: Name, name: name, widget: string }
              - { label: URL, name: url, widget: string }

      - label: Projects
        name: projects
        file: data/projects.md
        fields:
          - { label: Title, name: title, widget: string, default: Projects }
          - label: Projects
            name: projects
            widget: list
            allow_add: true
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Description, name: description, widget: text }
              - { label: URL, name: url, widget: string }
              - { label: Date, name: date, widget: datetime }
      - label: About
        name: about
        file: data/about.md
        fields:
          - { label: Body, name: body, widget: markdown }
