backend:
  name: github
  repo: phongduong/portfolio
  branch: master
publish_mode: editorial_workflow
media_folder: ".vuepress/public/images"
public_folder: ".vuepress/dist"
collections:
  - name: "project" 
    label: "Project"
    folder: "projects" 
    create: true 
    slug: "{{slug}}" 
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "title", widget: "string"}
      - {label: "Release Date", name: "date", widget: "datetime"}
      - {label: "Logo", name: "logo", widget: "image"}