backend:
  name: git-gateway
  accept_roles: 
    - admin
  # name: github
  # repo: phongduong/my-portfolio
  branch: master
publish_mode: editorial_workflow
media_folder: ".vuepress/public/images/upload"
public_folder: "images/upload"
collections:
  - name: "project"
    label: "Project"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          default: false,
        }
      - { label: "Release Date", name: "date", widget: "date" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Public URL", name: "public-url", widget: "string" }
      - { label: "Type", name: "type", widget: "string", default: "project" }
  - name: "contact"
    label: "Contact"
    folder: "contacts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Type", name: "type", widget: "string", default: "contact" }
